# Variables to be configured during pipeline creation/execution
# workGroupId
# environment
# location
# azureServiceConnectionName
# instance

variables: 
  directory: 'integration-environment-resources' 
  resourceGroupUsage: 'ise'

trigger:
 branches:
   include:
     - master
 paths:
   include:
     - /integration-environment-resources

stages:
- stage: Validation
  variables: 
    resourceDirectory: $(Build.Repository.LocalPath)\$(directory)
  jobs:
  - template: ../pipeline-templates/deploy-azure.yml
    parameters: 
      deploymentMode: Incremental
      resourceDirectory: $(resourceDirectory)
      workGroupId: $(workGroupId)
      environment: $(environment)
      azureServiceConnectionName: $(azureServiceConnectionName)
      location: $(location)
      resourceGroupUsage: $(resourceGroupUsage)
      instance: $(instance)